# Generated by Django 5.1.2 on 2025-02-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('campus', models.CharField(choices=[('Diamantina', 'Diamantina'), ('Janaúba', 'Janaúba'), ('Mucuri', 'Mucuri'), ('Unaí', 'Unaí')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='chapas/')),
            ],
        ),
    ]
