# Generated by Django 5.1.2 on 2025-02-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chapamembro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapaMembro',
        ),
    ]
