# Generated by Django 5.1.2 on 2025-02-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_membrochapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrochapa',
            name='campus',
            field=models.CharField(choices=[('Diamantina', 'Diamantina'), ('Janaúba', 'Janaúba'), ('Mucuri', 'Mucuri'), ('Unaí', 'Unaí')], max_length=20),
        ),
        migrations.AlterField(
            model_name='membrochapa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='membros_chapa/'),
        ),
    ]
