# Generated by Django 5.1.2 on 2025-02-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_membrochapa_campus_alter_membrochapa_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('valor_aproximado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campi', models.CharField(max_length=100)),
            ],
        ),
    ]
