# Generated by Django 5.1.2 on 2025-02-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patrimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
