# Generated by Django 5.1.2 on 2025-02-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_financeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='local',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='nome',
        ),
        migrations.AddField(
            model_name='evento',
            name='horario',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='evento',
            name='link_compra',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='parceiros',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='titulo',
            field=models.CharField(default='Evento sem título', max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(),
        ),
    ]
