# Generated by Django 5.1.2 on 2025-02-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_evento_descricao_remove_evento_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evento',
            name='parceiros',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
