# Generated by Django 5.1.2 on 2025-03-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_evento_horario_alter_evento_parceiros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
