# Generated by Django 5.2.3 on 2025-06-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerChapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Imagem principal do banner da chapa.', upload_to='banners_chapa/')),
                ('titulo', models.CharField(default='Chapa', help_text='Título exibido no banner.', max_length=255)),
                ('subtitulo', models.CharField(default='Conheça os membros da chapa', help_text='Subtítulo exibido no banner.', max_length=255)),
                ('ativo', models.BooleanField(default=True, help_text='Apenas o banner ativo será exibido.')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner da Chapa',
                'verbose_name_plural': 'Banners da Chapa',
            },
        ),
    ]
