# Generated by Django 5.2.3 on 2025-08-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_bannerchapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.AlterModelOptions(
            name='edital',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='atualizacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='atualizacoes/'),
        ),
    ]
